version: "3.9"

services:
  time-mgt-umi:
    restart: "always"
    build:
      context: ./time-mgt-umi
      dockerfile: docker/Dockerfile
    image: ngekaworu/time-mgt-umi
    container_name: time-mgt-umi
    networks:
      - frontend

  time-mgt-go:
    restart: "always"
    build:
      context: ./time-mgt-go
      dockerfile: docker/Dockerfile
    image: ngekaworu/time-mgt-go
    container_name: time-mgt-go
    environment:
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:?mongo url is required}
      REDIS: ${REDIS:?redis url is required}
      DB: ${DB:-time-mgt}
      UC: ${UC:-http://user-center}
    networks:
      - backend
    depends_on:
      - mongo
      - redis

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
